 import 'package:flutter/material.dart';
import '../../core/app_export.dart';

/// Helper class for managing themes and colors.
class ThemeHelper {
  // The current app theme
  final _appTheme = PrefUtils().getThemeData();

// A map of custom color themes supported by the app
  final Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors(),
   };

// A map of color schemes supported by the app
  final Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme,
   };

  /// Changes the app theme to [newTheme].
  void changeTheme(String newTheme) {
    PrefUtils().setThemeData(newTheme);
    Get.forceAppUpdate();
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(

      fontFamily: 'Almarai',
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      primaryColor: colorScheme.primary,
      primaryColorLight:colorScheme.primary,
      scaffoldBackgroundColor: colorScheme.onPrimaryContainer,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: colorScheme.primary,
          foregroundColor: Colors.white,
          textStyle: TextStyle(fontSize: 16.0.fSize,fontFamily: 'Almarai'),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(15.h),
          ),
          shadowColor: colorScheme.primary,
          elevation: 10,
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.all(20.h),
        ),
      ),
      dropdownMenuTheme: DropdownMenuThemeData(
        menuStyle: MenuStyle(
        ),
        textStyle: TextStyle(
          color: Colors.black
        ),
        inputDecorationTheme: InputDecorationTheme(
          border: OutlineInputBorder()
        )
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Colors.transparent,
          side: BorderSide(
            color: appTheme.blue50,
            width: 1.h,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(5.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      dialogTheme:DialogThemeData(
        insetPadding: EdgeInsets.all(20),
        titleTextStyle: TextStyle(
          fontSize: 24.fSize,
          fontFamily: 'Almarai',
          fontWeight: FontWeight.w700,
          color: colorScheme.primary
        ),
      ) ,
      listTileTheme: ListTileThemeData(
        titleTextStyle: TextStyle(fontSize: 20 .fSize,fontFamily: 'Almarai',color: Colors.black),
        subtitleTextStyle: TextStyle(fontSize: 16 .fSize,fontFamily: 'Almarai',color: Colors.black),
      ),
      dividerTheme: DividerThemeData(
        thickness: 1,
        space: 1,
        color:Colors.black26,
      ),
      textButtonTheme: TextButtonThemeData(
        style: TextButton.styleFrom(
          foregroundColor: PrimaryColors().primary2
        )
      ),
      tabBarTheme: TabBarThemeData(
        dividerColor: Colors.black26
      ),
      appBarTheme: AppBarTheme(
        backgroundColor: ColorSchemes.primaryColorScheme.primary,
            foregroundColor: Colors.white
      ) ,

      floatingActionButtonTheme: FloatingActionButtonThemeData(
        backgroundColor: ColorSchemes.primaryColorScheme.primary,
        foregroundColor: Colors.white,

      )
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodySmall: TextStyle(
          color: appTheme.blueGray300,
          fontSize: 12.fSize,
          fontFamily: 'Almarai',
          fontWeight: FontWeight.w400,
        ),
        headlineSmall: TextStyle(
          color: colorScheme.onPrimaryContainer,
          fontSize: 24.fSize,
          fontFamily: 'Almarai',
          fontWeight: FontWeight.w700,
        ),
        labelLarge: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: 12.fSize,
          fontFamily: 'Almarai',
          fontWeight: FontWeight.w700,
        ),
        labelMedium: TextStyle(
          color: appTheme.pink300,
          fontSize: 10.fSize,
          fontFamily: 'Almarai',
          fontWeight: FontWeight.w700,
        ),
        titleLarge: TextStyle(
          color: colorScheme.primary,
          fontSize: 20.fSize,
          fontFamily: 'Almarai',
          fontWeight: FontWeight.w700,
        ),
        titleMedium: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: 16.fSize,
          fontFamily: 'Almarai',
          fontWeight: FontWeight.w700,
        ),
        titleSmall: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: 14.fSize,
          fontFamily: 'Almarai',
          fontWeight: FontWeight.w700,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFF8417F4),
    secondaryContainer:Colors.white,
     secondary:Color(0XFF8417F4),
    // On colors(text colors)
    onPrimary: Colors.white,//Color(0XFF230B41),
    onPrimaryContainer: Colors.white ,//Color(0XFFFFF3F4),
  );


}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Amber
  Color get amber500 => Color(0XFFFFC107);

  // Blue
  Color get blue50 => Color(0XFFEAEFFF);
  Color get blueA200 => Color(0XFF4091FF);

  // BlueGray
  Color get blueGray300 => Color(0XFF9098B1);

  // Gray
  Color get gray400 => Color(0XFFC4C4C4);

  // Indigo
  Color get indigoA200 => Color(0XFF5B61F4);

  // LightBlue
  Color get lightBlue600 => Color(0XFF039BE5);

  // Pink
  Color get pink300 => Color(0XFFFB7181);

  // Yellow
  Color get yellow700 => Color(0XFFFFC732);
  Color get primary2 => Color(0xFF8417F4);
}

/// Class containing custom colors for a secondary theme.

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
